#192_4_nc

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_0/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_0 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=0 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_nc_0.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_1/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_1 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=1 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_nc_1.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_2/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_2 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=2 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_nc_2.txt &&
 
~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_3/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_3 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=3 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_nc_3.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_4/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_4 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=4 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_nc_4.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_5/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_5 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=5 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_nc_5.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_6/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_6 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=6 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_nc_6.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_7/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_7 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=7 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_nc_7.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_8/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_nc_8 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=8 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_nc_8.txt &&

#192_4_c
~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_0/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_0 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=0 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_c_0.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_1/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_1 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=1 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_c_1.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_2/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_2 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=2 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_c_2.txt &&
 
~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_3/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_3 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=3 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_c_3.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_4/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_4 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=4 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_c_4.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_5/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_5 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=5 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_c_5.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_6/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_6 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=6 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_c_6.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_7/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_7 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=7 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_c_7.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_8/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_4_c_8 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=4 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=8 >> /u/home/twayana/stats/mcf_s/final_collection/192_4_c_8.txt &&

#192_6_nc

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_0/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_0 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=0 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_nc_0.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_1/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_1 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=1 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_nc_1.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_2/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_2 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=2 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_nc_2.txt &&
 
~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_3/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_3 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=3 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_nc_3.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_4/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_4 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=4 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_nc_4.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_5/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_5 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=5 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_nc_5.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_6/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_6 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=6 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_nc_6.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_7/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_7 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=7 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_nc_7.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_8/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_nc_8 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=8 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_nc_8.txt &&

#192_6_c
~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_0/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_0 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=0 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_c_0.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_1/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_1 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=1 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_c_1.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_2/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_2 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=2 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_c_2.txt &&
 
~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_3/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_3 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=3 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_c_3.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_4/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_4 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=4 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_c_4.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_5/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_5 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=5 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_c_5.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_6/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_6 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=6 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_c_6.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_7/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_7 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=7 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_c_7.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_8/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_6_c_8 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=6 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=8 >> /u/home/twayana/stats/mcf_s/final_collection/192_6_c_8.txt &&

#192_8_nc

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_0/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_0 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=0 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_nc_0.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_1/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_1 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=1 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_nc_1.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_2/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_2 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=2 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_nc_2.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_3/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_3 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=3 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_nc_3.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_4/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_4 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=4 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_nc_4.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_5/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_5 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=5 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_nc_5.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_6/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_6 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=6 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_nc_6.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_7/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_7 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=7 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_nc_7.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_8/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_nc_8 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=8 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_nc_8.txt &&

#192_8_c
~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_0/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_0 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=0 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_c_0.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_1/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_1 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=1 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_c_1.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_2/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_2 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=2 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_c_2.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_3/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_3 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=3 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_c_3.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_4/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_4 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=4 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_c_4.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_5/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_5 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=5 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_c_5.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_6/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_6 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=6 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_c_6.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_7/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_7 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=7 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_c_7.txt &&

~/sim/gem5/build/X86/gem5.opt --debug-flags=O3PipeView --debug-start=0 --debug-file=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_8/trace.out --outdir=/u/home/twayana/stats/mcf_s/final_collection/192_8_c_8 ~/sim/gem5/configs/example/se.py --cmd=/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/build/build_base_initial-m64.0000/mcf_s --options="/u/home/twayana/sim/spec-cpu/benchspec/CPU/605.mcf_s/run/run_base_refspeed_initial-m64.0000/inp.in" --mem-size=8GB --cpu-type=DerivO3CPU --num-cpu=2 --maxinsts=1000000 --caches --l2cache --l1d_size=32kB --l1i_size=32kB --l2_size=512kB --prob-hw-counters=1 --prob-hw-counters-size=192B --prob-hw-counters-depth=8 --prob-hw-counters-conservative-update=1 --l1i-hwp-type=StridePrefetcher --l1d-hwp-type=StridePrefetcher --l2-hwp-type=StridePrefetcher --mem-type=DDR4_2400_4x16 --prob-hw-counters-group=8 >> /u/home/twayana/stats/mcf_s/final_collection/192_8_c_8.txt



